# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'zhihu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for zhihu
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SDAutoLayout'
pod 'MJExtension'
end
